# need 4 gpus

project: coconut
save_path: YOUR_PATH_TO_SAVE_THE_MODEL
name: prosqa-internalize

only_eval: True

coconut: False
cot: False
no_thoughts: False
no_cot: False
internalize_cot: True

c_thought: 0
epochs_per_stage: 5
max_latent_stage: 6
pad_latent_to_max: False

save_only_improve: False
uniform_prob: 0.0
model_id: openai-community/gpt2
load_model_path: YOUR_PATH_TO_SAVE_THE_MODEL/prosqa-internalize/checkpoint_28
seed: 0
resume: 40
bf16: False
train_path: data/prosqa_train.json
val_path: data/prosqa_test.json
reset_optimizer: True
batch_size_training: 32
debug: False
gradient_accumulation_steps: 1
num_epochs: 50
lr: !!float "1e-4"
weight_decay: 0.01
